In [1]:
#Read in data as 1D array (includes 1s)

import numpy as np
with open('new1ceumatrix.txt') as data_file:
    data = data_file.read()

arr = np.fromstring(data, sep=' ')

In [2]:
#Determining size of 1D array

from sys import getsizeof
getsizeof(arr)

345253656

In [3]:
arr.nbytes

345253560

In [4]:
arr

#To form 2d array (symmetrical about the diagonal)

from scipy.spatial.distance import squareform
x1 = squareform(arr, checks=True)

In [5]:
x1

array([[0.00000e+00, 1.00000e+00, 6.31922e-04, ..., 4.58382e-03,
        4.58382e-03, 2.00642e-02],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, ..., 4.22434e-03,
        4.22434e-03, 1.00430e-03],
       [6.31922e-04, 1.00000e+00, 0.00000e+00, ..., 9.38444e-03,
        9.38444e-03, 9.91116e-03],
       ...,
       [4.58382e-03, 4.22434e-03, 9.38444e-03, ..., 0.00000e+00,
        1.00000e+00, 7.16759e-02],
       [4.58382e-03, 4.22434e-03, 9.38444e-03, ..., 1.00000e+00,
        0.00000e+00, 1.00000e+00],
       [2.00642e-02, 1.00430e-03, 9.91116e-03, ..., 7.16759e-02,
        1.00000e+00, 0.00000e+00]])

In [6]:
x1.shape

(9291, 9291)

In [7]:
#Determining size of 2D array

getsizeof(x1)

690581560

In [8]:
x1.nbytes

690581448

In [9]:
#Attempt to use np.tril, np.tril_indices - kernel crashed with high enough argument

#iu1 = np.triu_indices(9291)
#x1[iu1] = 0

In [10]:
#Function to assign 0s to upper triangle of matrix, hence making it asymmetric and obtaining matrix with values only in the lower triangle

def lowertri(x):
    for i in range(len(x)):
        for j in range(len(x[i])):
            if i<=j:
                x[i][j]=0
    return x

In [11]:
x4 = lowertri(x1)

In [12]:
x4[0:5,0:5]

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00],
       [6.31922e-04, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00],
       [5.53328e-04, 8.75628e-01, 1.00000e+00, 0.00000e+00, 0.00000e+00],
       [1.76478e-03, 1.05421e-02, 9.23094e-03, 1.00000e+00, 0.00000e+00]])

In [13]:
x4

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [6.31922e-04, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [4.58382e-03, 4.22434e-03, 9.38444e-03, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.58382e-03, 4.22434e-03, 9.38444e-03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.00642e-02, 1.00430e-03, 9.91116e-03, ..., 7.16759e-02,
        1.00000e+00, 0.00000e+00]])

In [14]:
getsizeof(x4)

690581560

In [15]:
x4.nbytes

690581448

In [16]:
#Testing 2D array by checking random positions

x4[9289,2304]

0.000379593

In [17]:
x4.dtype.name

'float64'

In [18]:
#Attempting to store data as 32-bit floats

x5 = x4.astype(np.float32)

In [19]:
import scipy
from scipy.sparse import tril
#scipy.sparse.tril(x4)

In [21]:
x5.nbytes

345290724