In [1]:
import allel
allel.__version__

'1.2.1'

In [2]:
import zarr
zarr.__version__

'2.4.0'

In [3]:
import numcodecs
numcodecs.__version__

'0.6.4'

In [4]:
import numpy as np
np.__version__

'1.18.5'

In [5]:
import sys

In [6]:
vcf_path = '../../data/external_public/1kg_phase3/haps/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz'

In [7]:
!ls -lh {vcf_path}

-rw-rw-r-- 1 abiddanda pi-jnovembre 205M Dec  6  2016 ../../data/external_public/1kg_phase3/haps/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz


In [8]:
zarr_path = '../../data/external_public/1kg_phase3/haps/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.zarr'

In [9]:
allel.vcf_to_zarr(vcf_path, zarr_path, group='22',fields='*', log=sys.stdout,overwrite=True)

[vcf_to_zarr] 65536 rows in 11.22s; chunk in 11.22s (5842 rows/s); 22:18539397
[vcf_to_zarr] 131072 rows in 25.60s; chunk in 14.39s (4554 rows/s); 22:21016127
[vcf_to_zarr] 196608 rows in 37.79s; chunk in 12.19s (5377 rows/s); 22:23236362
[vcf_to_zarr] 262144 rows in 50.06s; chunk in 12.26s (5343 rows/s); 22:25227844
[vcf_to_zarr] 327680 rows in 62.48s; chunk in 12.43s (5273 rows/s); 22:27285434
[vcf_to_zarr] 393216 rows in 74.72s; chunk in 12.23s (5357 rows/s); 22:29572822
[vcf_to_zarr] 458752 rows in 86.99s; chunk in 12.27s (5341 rows/s); 22:31900536
[vcf_to_zarr] 524288 rows in 99.31s; chunk in 12.32s (5318 rows/s); 22:34069864
[vcf_to_zarr] 589824 rows in 111.47s; chunk in 12.16s (5389 rows/s); 22:36053392
[vcf_to_zarr] 655360 rows in 123.77s; chunk in 12.30s (5326 rows/s); 22:38088395
[vcf_to_zarr] 720896 rows in 135.70s; chunk in 11.93s (5494 rows/s); 22:40216200
[vcf_to_zarr] 786432 rows in 147.94s; chunk in 12.25s (5351 rows/s); 22:42597446
[vcf_to_zarr] 851968 rows

In [10]:
callset = zarr.open_group(zarr_path, mode='r')

In [11]:
callset.tree(expand=True)

ModuleNotFoundError: No module named 'ipytree'

/
 ├── 21
 │   ├── calldata
 │   │   └── GT (65536, 2504, 2) int8
 │   ├── samples (2504,) object
 │   └── variants
 │       ├── AA (65536,) object
 │       ├── AC (65536, 3) int32
 │       ├── AF (65536, 3) float32
 │       ├── AFR_AF (65536, 3) float32
 │       ├── ALT (0, 3) object
 │       ├── AMR_AF (0, 3) float32
 │       ├── AN (0,) int32
 │       ├── CHROM (0,) object
 │       ├── CIEND (0, 2) int32
 │       ├── CIPOS (0, 2) int32
 │       ├── CS (0,) object
 │       ├── DP (0,) int32
 │       ├── EAS_AF (0, 3) float32
 │       ├── END (0,) int32
 │       ├── EUR_AF (0, 3) float32
 │       ├── EX_TARGET (0,) bool
 │       ├── FILTER_PASS (0,) bool
 │       ├── ID (0,) object
 │       ├── IMPRECISE (0,) bool
 │       ├── MC (0,) object
 │       ├── MEINFO (0, 4) object
 │       ├── MEND (0,) int32
 │       ├── MLEN (0,) int32
 │       ├── MSTART (0,) int32
 │       ├── MULTI_ALLELIC (0,) bool
 │       ├── NS (0,) int32
 │       ├── POS (0,) int32
 │       ├── QUAL (0,) float32
 

In [12]:
gt_zarr = callset['22/calldata/GT']
gt_zarr.info

Name               : /22/calldata/GT
Type               : zarr.core.Array
Data type          : int8
Shape              : (1103547, 2504, 2)
Chunk shape        : (65536, 64, 2)
Order              : C
Read-only          : True
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 5526563376 (5.1G)
No. bytes stored   : 293489687 (279.9M)
Storage ratio      : 18.8
Chunks initialized : 680/680

In [13]:
pos = allel.SortedIndex(callset['22/variants/POS'])
pos

<SortedIndex shape=(1103547,) dtype=int32>
[16050075, 16050115, 16050213, 16050319, 16050527, ..., 51241342, 51241386, 51244163, 51244205, 51244237]

In [14]:
loc_region = pos.locate_range(20000000,20100000)
loc_region

slice(108029, 111127, None)

In [15]:
gt_region = allel.GenotypeArray(gt_zarr[loc_region])
gt_region

<GenotypeArray shape=(3098, 2504, 2) dtype=int8>
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
...
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0

In [16]:
multi_allelic = callset['22/variants/MULTI_ALLELIC'][:]
multi_allelic

array([False, False, False, ..., False, False, False])

In [17]:
afr_af=callset['22/variants/AFR_AF'][:]
afr_af

array([[0.    ,    nan,    nan],
       [0.0234,    nan,    nan],
       [0.0272,    nan,    nan],
       ...,
       [0.    ,    nan,    nan],
       [0.    ,    nan,    nan],
       [0.    ,    nan,    nan]], dtype=float32)

In [18]:
loc_variant_selection = ~multi_allelic & (afr_af[:,0]>0.05)
loc_variant_selection

array([False, False, False, ..., False, False, False])

In [19]:
len(afr_af)

1103547

In [20]:
np.count_nonzero(loc_variant_selection)

138275

In [21]:
gt_dask = allel.GenotypeDaskArray(gt_zarr)
gt_dask

<GenotypeDaskArray shape=(1103547, 2504, 2) dtype=int8>

In [22]:
gt_variant_selection = gt_dask.compress(loc_variant_selection, axis=0).compute()
gt_variant_selection

<GenotypeArray shape=(138275, 2504, 2) dtype=int8>
0/1 0/0 0/0 0/0 0/0 ... 1/0 0/1 0/0 0/0 0/0
0/1 0/0 0/0 1/0 1/0 ... 1/1 0/1 1/1 0/0 1/1
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
...
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 1/0 0/0 0/0 0/0